### PR TITLE
Local Game State Implementation

### PR DESCRIPTION
**Pull request by Abhay-2811**
The game state is initialized on init command and is updated every time action is called. Before performing any action every player sends a POST request to `/checkmove` that returns true if the move is valid but panics if the move is invalid.

### CODE REVIEW

**Comment by nlok5923** [comment]
Thanks for the pr, Once the masking and unmasking is done will test the game and review over the changes. Most prolly over the weekend.

**Comment by Abhay-2811** [comment]
@nlok5923  Can we merge this so I can get started on issue #11

**Review by nlok5923 — APPROVED** [review]
gtg

**Comment by nlok5923** [comment]
Sure, and immediately after fixing #11 prolly you can start working on the `aze-cli show hand` command. Meanwhile ig #7 will be merged ig.

**Pull request merged**
